# Categories
restaurante = Restaurante.create(cnpj: '86.587.634/0001-08', endereco: 'R. Rui Barbosa, 239 E, Chapecó-SC', nome: 'Signos da Lua')

skol     = Cardapio.create(nome: 'Cerveja Skol',   descricao: '600ml', preco: '8.00', restaurante: restaurante)
brahma   = Cardapio.create(nome: 'Cerveja Brahma', descricao: '600ml', preco: '8.00', restaurante: restaurante)
caipira  = Cardapio.create(nome: 'Caipira',        descricao: 'Caipira de limão, 500ml', preco: '10.00', restaurante: restaurante)
caipira2 = Cardapio.create(nome: 'Caipira',        descricao: 'Caipira de morango, 500ml', preco: '10.00', restaurante: restaurante)
coca     = Cardapio.create(nome: 'Coca-cola',      descricao: 'Lata', preco: '5.00', restaurante: restaurante)
pepsi    = Cardapio.create(nome: 'Pepsi',          descricao: 'Lata', preco: '5.00', restaurante: restaurante)
guarana  = Cardapio.create(nome: 'Guarana',        descricao: 'Lata', preco: '5.00', restaurante: restaurante)
agua     = Cardapio.create(nome: 'Água',           descricao: 'Água s/ gás', preco: '3.00', restaurante: restaurante)
agua     = Cardapio.create(nome: 'Água',           descricao: 'Água c/ gás', preco: '3.00', restaurante: restaurante)
suco1    = Cardapio.create(nome: 'Suco',           descricao: 'Suco de pêssego, 500ml', preco: '6.00', restaurante: restaurante)
suco2    = Cardapio.create(nome: 'Suco',           descricao: 'Suco de morango, 500ml', preco: '6.00', restaurante: restaurante)
suco3    = Cardapio.create(nome: 'Suco',           descricao: 'Suco de laranja, 500ml', preco: '6.00', restaurante: restaurante)
combo1   = Cardapio.create(nome: 'Combo 1',        descricao: '800g', adicionais:'Batata-frita, alcatras em tiras', preco: '20.00', restaurante: restaurante)
combo2   = Cardapio.create(nome: 'Combo 2',        descricao: '800g', adicionais:'Batata-frita, polenta, alcatras em tiras', preco: '25.00', restaurante: restaurante)
combo3   = Cardapio.create(nome: 'Combo 3',        descricao: '800g', adicionais:'Batata-frita, tilapia empanada', preco: '18.00', restaurante: restaurante)
combo4   = Cardapio.create(nome: 'Combo 4',        descricao: '800g', adicionais:'Mandioca frita, alcatras em tiras', preco: '20.00', restaurante: restaurante)
combo5   = Cardapio.create(nome: 'Combo 5',        descricao: '800g', adicionais:'Batata-frita, file acebolado, frango a passarinho', preco: '28.00', restaurante: restaurante)
combo6   = Cardapio.create(nome: 'Combo 6',        descricao: '900g', adicionais:'Batata-frita, aneis de cebola, alcatras em tiras', preco: '23.00', restaurante: restaurante)
batata   = Cardapio.create(nome: 'Batata-frita',   descricao: '500g', adicionais:'Bacon e queijo', preco: '18.00', restaurante: restaurante)
batata   = Cardapio.create(nome: 'Batata-frita',   descricao: '500g', preco: '12.00', restaurante: restaurante)
cebola   = Cardapio.create(nome: 'Aneis de cebola',descricao: '500g', preco: '12.00', restaurante: restaurante)
mandioca = Cardapio.create(nome: 'Mandioca frita', descricao: '500g', preco: '12.00', restaurante: restaurante)
polenta  = Cardapio.create(nome: 'Polenta frita',  descricao: '500g', preco: '13.00', restaurante: restaurante)
kibe     = Cardapio.create(nome: 'Kibe',           descricao: 'porção de 300g', preco: '15.00', restaurante: restaurante)

mesa1  = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa2  = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa3  = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa4  = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa5  = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa6  = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa7  = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa8  = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa9  = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa10 = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa11 = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa12 = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa13 = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa14 = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)
mesa15 = Mesa.create(status: 'false', tempo_entrega: '00:00:0000', restaurante: restaurante)

comanda1 = Comanda.create(nome_cliente: 'Libra')
comanda2 = Comanda.create(nome_cliente: 'Peixes')
comanda3 = Comanda.create(nome_cliente: 'Áries')
comanda4 = Comanda.create(nome_cliente: 'Touro')
comanda5 = Comanda.create(nome_cliente: 'Leão')
comanda6 = Comanda.create(nome_cliente: 'Virgem')
comanda7 = Comanda.create(nome_cliente: 'Sagitário')
comanda8 = Comanda.create(nome_cliente: 'Escorpião')
comanda9 = Comanda.create(nome_cliente: 'Gêmeos')
comanda10 = Comanda.create(nome_cliente: 'Câncer')
comanda11= Comanda.create(nome_cliente: 'Aquário')
comanda12 = Comanda.create(nome_cliente: 'Capricórnio')

mesa1.compras.create(comanda: comanda1, cardapio: skol.id)
mesa1.compras.create(comanda: comanda1, cardapio: combo1.id)
mesa2.compras.create(comanda: comanda2, cardapio: brahma.id)
mesa2.compras.create(comanda: comanda3, cardapio: batata.id)
mesa2.compras.create(comanda: comanda4, cardapio: guarana.id)
mesa2.compras.create(comanda: comanda5, cardapio: coca.id)
mesa3.compras.create(comanda: comanda3, cardapio: brahma.id)
mesa3.compras.create(comanda: comanda6, cardapio: combo3.id)
mesa4.compras.create(comanda: comanda7, cardapio: brahma.id)
mesa4.compras.create(comanda: comanda7, cardapio: mandioca.id)
mesa5.compras.create(comanda: comanda8, cardapio: kibe.id)
mesa5.compras.create(comanda: comanda9, cardapio: guarana.id)
mesa10.compras.create(comanda: comanda10, cardapio: combo2.id)
mesa10.compras.create(comanda: comanda11, cardapio: combo3.id)
mesa10.compras.create(comanda: comanda12, cardapio: brahma.id)